apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-cicd
  template:
    metadata:
      labels:
        app: springboot-cicd
    spec:
      containers:
        - name: springboot-cicd
          image: ${IMAGE_REPO}:${IMAGE_TAG}
          ports:
            - containerPort: 8080
