apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-cicd
  template:
    metadata:
      labels:
        app: springboot-cicd
    spec:
      containers:
        - name: springboot-cicd
          image: kiranwaredockerpoc/springboot-cicd:20
          ports:
            - containerPort: 8080
