apiVersion: v1
kind: Service
metadata:
  name: springboot-cicd-service
spec:
  type: NodePort
  selector:
    app: springboot-cicd   # must match the labels in deployment.yaml
  ports:
    - name: http
      port: 8080           # Service port inside cluster
      targetPort: 8080     # Container port from deployment
      nodePort: 30080      # NodePort on minikube node (30000â€“32767)